---
# tasks file for elasticsearch

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - elasticsearch

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - elasticsearch

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - elasticsearch

- name: Create Elasticsearch defaults file
  become: yes
  template:
    src: elasticsearch.default.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0660
  notify:
    - restart elasticsearch
  tags:
    - elasticsearch

- name: Create Elasticsearch configuration file
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch
  tags:
    - elasticsearch

- name: Create Elasticsearch logging configuration file
  become: yes
  template:
    src: log4j2.properties.j2
    dest: /etc/elasticsearch/log4j2.properties
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch
  tags:
    - elasticsearch

- name: Create JVM options configuration file
  become: yes
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch
  tags:
    - elasticsearch

- name: Ensure Elasticsearch is started and enabled on boot
  become: yes
  service:
    name: "{{ elasticsearch_service_name }}"
    state: started
    enabled: yes
  tags:
    - elasticsearch
