---
# tasks file for elasticsearch

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: elasticsearch

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: elasticsearch

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: elasticsearch

- name: Create Elasticsearch defaults file
  template: >
    src=elasticsearch.default.j2
    dest=/etc/default/elasticsearch
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch
  tags: elasticsearch

- name: Create Elasticsearch configuration file
  template: >
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch
  tags: elasticsearch

- name: Create Elasticsearch logging configuration file
  template: >
    src=logging.yml.j2
    dest=/etc/elasticsearch/logging.yml
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch
  tags: elasticsearch

- name: Ensure Elasticsearch is started and enabled on boot
  service: name={{ elasticsearch_service_name }} state=started enabled=yes
  tags: elasticsearch
